# ---------- global settings ----------
[cmake]
version       = "3.30"
cmkr-include  = "cmake/cmkr.cmake"
build-dir     = "out"
config        = "Release"

[project]
name          = "MegaVoltsPP"
languages     = ["C", "CXX"]
msvc-runtime = "static"
include-after = ["cmake/PlatformFlags.cmake"]

[vcpkg]
version = "2025.06.13"
packages = [
    "fmt",
    "crashpad",
	"mariadb-connector-cpp",
	"libsodium",
    "openssl",
    "libpqxx",
    "gtest"
]
overlay = "vcpkg-overlay"

[find-package.fmt]
[find-package.crashpad]
[find-package.unofficial-mariadb-connector-cpp]
[find-package.OpenSSL]
[find-package.libpqxx]
[find-package.GTest]

[subdir.deps]
[subdir.common]
[subdir.tests]

[template.server-executable]
type                = "executable"
compile-definitions = [
    "RELEASE_1_0_3",
    "$<$<PLATFORM_ID:Windows>:_CRT_SECURE_NO_WARNINGS>",
    "$<$<PLATFORM_ID:Windows>:_WIN32_WINNT=0x0A00>"
]
compile-features = ["cxx_std_23"]
properties.MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>"
link-libraries = ["asio", "boost_unordered", "thread-pool", "rapidjson", "monocypher", "magic_enum", "fmt::fmt", "crashpad::crashpad", "unofficial::mariadb-connector-cpp::mariadbcpp", "libpqxx::pqxx", "OpenSSL::SSL", "OpenSSL::Crypto", "common"]

[target.front]
type                = "server-executable"   # inherits template from root
sources             = ["src/Front/**.cpp", "src/Front/**.h"]
include-directories = ["."]

[target.main]
type                = "server-executable"   # inherits template from root
sources             = ["src/Main/**.cpp", "src/Main/**.h"]
include-directories = [".", "src/Main"]

[target.cast]
type                = "server-executable"   # inherits template from root
sources             = ["src/Cast/**.cpp", "src/Cast/**.h"]
include-directories = ["."]

[[install]]
targets = ["front", "main", "cast"]
destination = "bin"
