services:
  linux-gcc-build:
    build:
      context: .
      dockerfile: docker/linux-build.Dockerfile
    image: megavoltspp/linux-gcc-build:local
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./out-docker-gcc:/workspace/out-docker-gcc
      - ./out-docker-cache-vcpkg:/root/.cache/vcpkg
    command: >
      bash -lc "
      export PATH=/usr/local/bin:/root/.local/bin:$$PATH &&
      cmake --version &&
      cmake -S . -B out-docker-gcc -G Ninja
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_CXX_SCAN_FOR_MODULES=OFF
      -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic &&
      cmake --build out-docker-gcc --target cast main front -j\$(nproc)
      "

  linux-clang-build:
    build:
      context: .
      dockerfile: docker/linux-build.Dockerfile
    image: megavoltspp/linux-clang-build:local
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./out-docker-clang:/workspace/out-docker-clang
      - ./out-docker-cache-vcpkg:/root/.cache/vcpkg
    command: >
      bash -lc "
      export PATH=/usr/local/bin:/root/.local/bin:$$PATH &&
      cmake --version &&
      cmake -S . -B out-docker-clang -G Ninja
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_CXX_SCAN_FOR_MODULES=OFF
      -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic &&
      cmake --build out-docker-clang --target cast main front -j\$(nproc)
      "
