[cmake]
version       = "3.30"
cmkr-include  = "cmake/cmkr.cmake"

[target.common]
compile-definitions = ["RELEASE_1_0_3", "_CRT_SECURE_NO_WARNINGS", "_WIN32_WINNT=0x0A00"]
compile-features = ["cxx_std_23"]

type    = "interface"
include-directories = [".", "BaseLib/otp", "BaseLib", "NetEngine", "NetEngine/Protocols"]
sources = [
    "BaseLib/otp/**.cpp", 
	"BaseLib/otp/**.h",
	"BaseLib/**.cpp", 
	"BaseLib/**.h",
	"NetEngine/**.cpp", 
	"NetEngine/**.h"
]

