option(MVPP_SANITIZE_ADDRESS   "Enable AddressSanitizer (ASan)"           OFF)
option(MVPP_SANITIZE_UNDEFINED "Enable UndefinedBehaviorSanitizer (UBSan)" OFF)
option(MVPP_SANITIZE_THREAD    "Enable ThreadSanitizer (TSan)"             OFF)

if (MVPP_SANITIZE_ADDRESS AND MVPP_SANITIZE_THREAD)
    message(FATAL_ERROR "ASan and TSan cannot be used together. Pick one.")
endif()

set(MVPP_SANITIZER_FLAGS "")

if (MVPP_SANITIZE_ADDRESS)
    if (MSVC AND NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        list(APPEND MVPP_SANITIZER_FLAGS "/fsanitize=address")
    else()
        list(APPEND MVPP_SANITIZER_FLAGS "-fsanitize=address" "-fno-omit-frame-pointer")
    endif()
    message(STATUS "AddressSanitizer enabled")
endif()

if (MVPP_SANITIZE_UNDEFINED)
    if (MSVC AND NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        message(WARNING "UBSan is not supported by MSVC cl.exe — skipping")
    else()
        list(APPEND MVPP_SANITIZER_FLAGS "-fsanitize=undefined" "-fno-sanitize-recover=undefined")
    endif()
    message(STATUS "UndefinedBehaviorSanitizer enabled")
endif()

if (MVPP_SANITIZE_THREAD)
    if (MSVC AND NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        message(WARNING "TSan is not supported by MSVC cl.exe — skipping")
    else()
        list(APPEND MVPP_SANITIZER_FLAGS "-fsanitize=thread")
    endif()
    message(STATUS "ThreadSanitizer enabled")
endif()

if (MVPP_SANITIZER_FLAGS)
    add_compile_options(${MVPP_SANITIZER_FLAGS})
    if (NOT (MSVC AND NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
        add_link_options(${MVPP_SANITIZER_FLAGS})
    endif()
endif()
